env:
  node: true
  es6: true
extends: ["eslint:recommended", "plugin:react/recommended"]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module
plugins:
  - react
rules:
  no-unused-vars: 
    - warn
    - argsIgnorePattern: next
  react/react-in-jsx-scope: null
